---
- name: Install and configure Nagios on workgroup computers
  hosts: all
  vars:
    nagios_agent_path: "files/nagios-agent.msi"
    nagios_server: "nagios.example.com"
  tasks:
  - name: Install Nagios agent
    win_package:
      path: "{{ nagios_agent_path }}"
      state: present

  - name: Configure Nagios agent
    win_reg_stat:
      path: "HKLM:\Software\Nagios"
      name: Server
      data: "{{ nagios_server }}"
      state: present
